# Generated by Django 2.1.7 on 2019-05-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=5)),
                ('imglink', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('abs', models.DecimalField(decimal_places=2, max_digits=7)),
                ('theme', models.CharField(max_length=30)),
            ],
        ),
    ]
