# Generated by Django 2.1.7 on 2019-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='json',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
